version: '3'

# Docker Services
services:
  # Fluent-Bit (Logging)
  fluent-bit:
    build:
      context: './docker/fluent-bit'
    command: /fluent-bit/bin/fluent-bit -i node_exporter_metrics -p path.procfs=/host/proc -p path.sysfs=/host/sys -o prometheus_exporter -p "add_label=host fluentbit" -f 1
    restart: unless-stopped
    ports:
      - '2020:2020'
      - '2021:2021'
      - '24224:24224'
      - '24224:24224/udp'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  otel:
    build:
      context: './docker/otel-collector'
    command: ['--config=/etc/otel-collector-config.yaml']
    ports:
    ports:
      - '1888:1888' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317:4317' # OTLP gRPC receiver
      - '55670:55679' # zpages extension

  cadvisor:
    build:
      context: './docker/cadvisor'
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
